version: 2.1

jobs:
  build:
    docker:
      - image: node:18
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run tests
          command: npm test -- --watchAll=false --verbose
      - run:
          name: Build application
          command: npm run build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build