version: 2.1

jobs:
  build:
    docker:
      - image: node:18
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Run tests
          command: npm test -- --watchAll=false --verbose
      - run:
          name: Build application
          command: npm run build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build